const domains = new Set([
  '10minutemail.com', '10minutemail.net', '10minutemail.org',
  'mailinator.com', 'mailinator.net', 'mailinator.org',
  'guerrillamail.com', 'guerrillamail.net', 'guerrillamail.org',
  'guerrillamail.biz', 'guerrillamailblock.com',
  'tempmail.com', 'tempmail.net', 'tempmail.org',
  'temp-mail.org', 'temp-mail.net', 'temp-mail.com',
  'throwaway.email', 'throwaway.com',
  'throwawayemail.com', 'throwawaymail.com',
  'yopmail.com', 'yopmail.net', 'yopmail.org',
  'sharklasers.com', 'spam4.me', 'spamgourmet.com',
  'spamfree24.org', 'spamfree24.net', 'spamfree24.com',
  'spam.la', 'spam.su', 'spamspot.com',
  'spamavert.com', 'spambob.com', 'spambob.net',
  'spambob.org', 'spambog.com', 'spambog.net',
  'spambog.org', 'spambox.us', 'spambox.me',
  'spamcero.com', 'spamcorptastic.com', 'spamcowboy.com',
  'spamcowboy.net', 'spamcowboy.org', 'spamday.com',
  'spamdecoy.net', 'spamex.com', 'spamfighter.cf',
  'spamfighter.ga', 'spamfighter.gq', 'spamfighter.ml',
  'spamfighter.tk', 'spamfree.eu', 'spamgoes.in',
  'spamherelots.com', 'spamhereplease.com', 'spamhole.com',
  'spamify.com', 'spaminator.de', 'spamkill.info',
  'spaml.com', 'spamlot.net', 'spammedic.com',
  'spammy.host', 'spamobox.com', 'spamout.net',
  'spamspy.com', 'spamstack.net', 'spamthis.co.uk',
  'spamthis.name', 'spamtrail.com', 'spamtrap.co',
  'spamtroll.net', 'spamwc.de', 'spamx.net',
  'temp-inbox.com', 'temp-mail.life', 'temp-mail.org',
  'tempail.com', 'tempemail.co', 'tempemail.com',
  'tempemail.net', 'tempemail.org', 'tempinbox.com',
  'tempmail.co', 'tempmail.it', 'tempmail.ml',
  'tempmail.tk', 'tempmail.ga', 'tempmail.gq',
  'tempmail.ws', 'tempomail.fr', 'temporary-mail.net',
  'temporary-email.com', 'temporarymail.org',
  'temporaryemail.net', 'temporaryemail.us',
  'temporaryforwarding.com', 'temporarioemail.com.br',
  'temporarily.de', 'temporomail.com', 'trash-mail.at',
  'trash-mail.com', 'trash-mail.de', 'trash-mail.net',
  'trash-me.com', 'trash2009.com', 'trash2010.com',
  'trash2011.com', 'trash247.com', 'trashbox.info',
  'trashcanmail.com', 'trashdevil.com', 'trashdevil.de',
  'trashemail.de', 'trashmail.at', 'trashmail.com',
  'trashmail.de', 'trashmail.me', 'trashmail.net',
  'trashmail.org', 'trashmail.ws', 'trashmailer.com',
  'trashmails.com', 'trashymail.com', 'trashymail.net',
  'tyldd.com', 'uggsrock.com', 'wegwerfmail.de',
  'wegwerfmail.net', 'wegwerfmail.org',
  'wh4f.org', 'whyspam.me', 'willselfdestruct.com',
  'winemaven.info', 'wronghead.com', 'wuzup.net',
  'xagloo.com', 'xemaps.com', 'xents.com', 'xing886.uu.gl',
  'xmail.com', 'xmaily.com', 'xoxox.cc', 'xoxy.net',
  'xpee.com', 'xperiae5.com', 'xrap.de', 'xs4all.nl',
  'xss.de', 'xtra.com', 'xww.ro', 'xyzmail.com',
  'yannmail.com', 'yapped.com', 'ycare.de', 'ycn.ro',
  'yeah.com', 'yebox.com', 'yedi.org', 'yep.it',
  'yermail.com', 'yert.ye.vc', 'yes.com', 'yhg.biz',
  'ynmrealty.com', 'yogamaven.com', 'yomail.info',
  'yoo.ro', 'yopmail.fr', 'yopmail.net',
  'yopmail.com', 'you-spam.com', 'youpy.com',
  'yourdomain.com', 'youremail.cf', 'youremail.ga',
  'youremail.gq', 'youremail.ml', 'youremail.tk',
  'yourlmao.com', 'yourtube.com', 'yuoia.com',
  'z1p.biz', 'za.com', 'zahav.net.il', 'zain.site',
  'zainmax.net', 'zaktouni.fr', 'zale.com',
  'zanima.me', 'zaym.com', 'zaz.com', 'zebins.com',
  'zebins.eu', 'zehnminutenmail.de', 'zemail.ga',
  'zemail.ml', 'zemail.tk', 'zep-hyr.com', 'zero-e.ml',
  'zerocrypt.ml', 'zetmail.com', 'zh.ax', 'zhewei.xyz',
  'zhouemail.510520.org', 'ziggo.nl', 'zilore.com',
  'zimail.com', 'zip.net', 'zipido.com', 'zippiex.com',
  'zipo.biz', 'zippymail.info', 'zipsendtest.com',
  'zomg.info', 'zoaxe.com', 'zoemail.com', 'zoemail.net',
  'zoemail.org', 'zombie-hive.com', 'zomg.info',
  'zumpat.com', 'zxcv.com', 'zxcvbnm.com', 'zybermail.com',
  'zymer.co', 'zymuying.com', 'zz.mk', 'zzz.com',
]);

export function isDisposableEmail(email) {
  const domain = email.split('@')[1]?.toLowerCase();
  return domain ? domains.has(domain) : false;
}

export default domains;
